//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public int IDLibro { get; set; }
        public string Autor { get; set; }
        public string TituloLibro { get; set; }
        public Nullable<int> Anio { get; set; }
        public string Editorial { get; set; }
    }
}
