//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;

    public partial class LibreriaEntities1 : DbContext
    {
        public LibreriaEntities1()
            : base("name=LibreriaEntities1")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Libro> Libro { get; set; }

        public virtual int sp_AgregaLibro(string autor, string tituloLibro, Nullable<int> anio, string editorial)
        {
            var autorParameter = autor != null ?
                new ObjectParameter("Autor", autor) :
                new ObjectParameter("Autor", typeof(string));

            var tituloLibroParameter = tituloLibro != null ?
                new ObjectParameter("TituloLibro", tituloLibro) :
                new ObjectParameter("TituloLibro", typeof(string));

            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));

            var editorialParameter = editorial != null ?
                new ObjectParameter("Editorial", editorial) :
                new ObjectParameter("Editorial", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AgregaLibro", autorParameter, tituloLibroParameter, anioParameter, editorialParameter);
        }

        public virtual int sp_BorrarLibroXAutor(string autor)
        {
            var autorParameter = autor != null ?
                new ObjectParameter("Autor", autor) :
                new ObjectParameter("Autor", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BorrarLibroXAutor", autorParameter);
        }

        public virtual int sp_BorrarLibroXEditorial(string editorial)
        {
            var editorialParameter = editorial != null ?
                new ObjectParameter("Editorial", editorial) :
                new ObjectParameter("Editorial", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BorrarLibroXEditorial", editorialParameter);
        }

        public virtual ObjectResult<sp_ConsultaXAnio_Result> sp_ConsultaXAnio(Nullable<int> anio)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultaXAnio_Result>("sp_ConsultaXAnio", anioParameter);
        }

        public virtual ObjectResult<sp_ConsultaXAutor_Result> sp_ConsultaXAutor(string autor)
        {
            var autorParameter = autor != null ?
                new ObjectParameter("Autor", autor) :
                new ObjectParameter("Autor", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultaXAutor_Result>("sp_ConsultaXAutor", autorParameter);
        }

        public virtual ObjectResult<sp_ConsultaXAutorFecha_Result> sp_ConsultaXAutorFecha(string autor, Nullable<int> fecha)
        {
            var autorParameter = autor != null ?
                new ObjectParameter("Autor", autor) :
                new ObjectParameter("Autor", typeof(string));

            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultaXAutorFecha_Result>("sp_ConsultaXAutorFecha", autorParameter, fechaParameter);
        }

        public virtual ObjectResult<sp_ConsultaXEditorial_Result> sp_ConsultaXEditorial(string editorial)
        {
            var editorialParameter = editorial != null ?
                new ObjectParameter("Editorial", editorial) :
                new ObjectParameter("Editorial", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultaXEditorial_Result>("sp_ConsultaXEditorial", editorialParameter);
        }

        public virtual ObjectResult<sp_ConsultaXLibro_Result> sp_ConsultaXLibro(string tituloLibro)
        {
            var tituloLibroParameter = tituloLibro != null ?
                new ObjectParameter("TituloLibro", tituloLibro) :
                new ObjectParameter("TituloLibro", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultaXLibro_Result>("sp_ConsultaXLibro", tituloLibroParameter);
        }
    }
}
